name: Maven CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Installer Maven et Java si nécessaire
        run: |
          if ! command -v mvn &> /dev/null
          then
            echo "Maven non trouvé : installation en cours..."
            sudo apt update
            sudo apt install -y maven openjdk-17-jdk
          fi
          echo "Versions installées :"
          mvn -v
          java -version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build (compilation uniquement)
        run: mvn clean compile

  tests:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit & integration tests
        run: mvn test

  deploy:
    runs-on: self-hosted
    needs: tests
    steps:
      - name: Préparer le repo sur la VM
        run: |
          cd ~
          if [ ! -d "brokerx" ]; then
            echo "Clonage initial du repo..."
            git clone https://github.com/SalahGhedda/BrokerX.git brokerx
          fi
          cd ~/brokerx
          git fetch origin
          git reset --hard origin/main
          git clean -fd

      - name: Build & Rebuild Docker image
        run: |
          cd ~/brokerx
          mvn clean package -DskipTests
          docker rm -f brokerx || true
          docker rmi brokerx:latest || true
          docker build -t brokerx:latest .

      - name: Fin du déploiement
        run: echo "Déploiement terminé - l'image est prête dans Docker."



