name: Maven CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Préparer le repo sur la VM
        run: |
          cd ~
          if [ ! -d "brokerx" ]; then
            echo "Clonage initial du repo..."
            git clone https://github.com/SalahGhedda/BrokerX.git
          fi
          cd brokerx
          echo "Mise à jour du repo..."
          git reset --hard
          git clean -fd
          git pull origin main

      - name: Build Maven et reconstruire l'image Docker
        run: |
          cd ~/brokerx
          mvn clean package -DskipTests
          docker rm -f brokerx || true
          docker rmi brokerx:latest || true
          docker build -t brokerx:latest .


